version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "flask-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-puerqpqdmto0"
s3_prefix = "flask-test"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
